name: Release

on:
  push:
    branches:
      - main   # O la rama que desees lanzar

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Saludito
        run: |
          echo "Buen trabajo ${{ github.actor }}. :)"
