name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          curl -sSL https://github.com/cocogitto/cocogitto/releases/download/v6.2.0/cocogitto-linux-amd64 -o /usr/local/bin/cog
          chmod +x /usr/local/bin/cog
          curl -fsSL https://cli.github.com/packages/githubcli.repo > /etc/apt/sources.list.d/githubcli.list
          sudo apt update
          sudo apt install gh

      - name: Ejecutar script de release
        run: bash ./release.sh
